window.KEY_POSITIONS_V2 = [
  {"id":"kp_poacher","name":"포처","simple":"fw","main":"shooting","sub":"speed","mental":"sense","team":"individual","desc":"수비 뒷공간을 파고드는 마무리형 공격수"},
  {"id":"kp_target_forward","name":"타겟 포워드","simple":"fw","main":"power","sub":"shooting","mental":"sense","team":"organization","desc":"몸싸움과 제공권으로 공격의 기준점이 되는 공격수"},
  {"id":"kp_false_nine","name":"펄스 나인","simple":"fw","main":"technique","sub":"passing","mental":"intelligence","team":"organization","desc":"전방에서 내려와 패스와 연계로 공간을 만드는 공격수"},
  {"id":"kp_wing_forward_l","name":"왼쪽 윙포워드","simple":"fw","main":"speed","sub":"technique","mental":"sense","team":"individual","desc":"측면 돌파와 컷인 슈팅에 강한 공격수"},
  {"id":"kp_wing_forward_r","name":"오른쪽 윙포워드","simple":"fw","main":"speed","sub":"technique","mental":"sense","team":"individual","desc":"오른쪽 측면에서 돌파와 찬스메이킹을 담당"},
  {"id":"kp_playmaker","name":"플레이메이커","simple":"mf","main":"technique","sub":"passing","mental":"intelligence","team":"organization","desc":"중앙에서 패스와 템포를 조율하는 미드필더"},
  {"id":"kp_trequartista","name":"트레콰르티스타","simple":"mf","main":"technique","sub":"shooting","mental":"sense","team":"individual","desc":"공격수와 미드필더 사이에서 결정적 장면을 만드는 선수"},
  {"id":"kp_box_to_box","name":"박스 투 박스","simple":"mf","main":"stamina","sub":"power","mental":"intelligence","team":"organization","desc":"공수 양면을 왕복하며 압박과 전개를 담당"},
  {"id":"kp_anchor","name":"앵커맨","simple":"mf","main":"defense","sub":"power","mental":"intelligence","team":"organization","desc":"수비라인 앞에서 위험 지역을 차단하는 미드필더"},
  {"id":"kp_wingback_l","name":"왼쪽 윙백","simple":"df","main":"stamina","sub":"speed","mental":"intelligence","team":"organization","desc":"측면 전진과 수비 복귀를 모두 수행"},
  {"id":"kp_wingback_r","name":"오른쪽 윙백","simple":"df","main":"stamina","sub":"speed","mental":"intelligence","team":"organization","desc":"오른쪽 측면 왕복과 크로스를 담당"},
  {"id":"kp_center_back","name":"센터백","simple":"df","main":"defense","sub":"power","mental":"intelligence","team":"organization","desc":"수비의 중심에서 라인을 지휘하고 경합을 이김"},
  {"id":"kp_sweeper","name":"스위퍼","simple":"df","main":"defense","sub":"technique","mental":"intelligence","team":"organization","desc":"수비 뒷공간을 커버하고 빌드업에 관여"},
  {"id":"kp_ball_playing_cb","name":"빌드업 센터백","simple":"df","main":"defense","sub":"passing","mental":"intelligence","team":"organization","desc":"후방에서 정확한 패스로 공격을 시작"},
  {"id":"kp_sweeper_keeper","name":"스위퍼 키퍼","simple":"gk","main":"goalkeeper","sub":"passing","mental":"intelligence","team":"organization","desc":"골문 수비와 후방 빌드업을 함께 담당"},
  {"id":"kp_shot_stopper","name":"슈팅 스토퍼","simple":"gk","main":"goalkeeper","sub":"power","mental":"sense","team":"individual","desc":"반사신경과 선방 능력에 특화된 골키퍼"},
  {"id":"kp_second_striker","name":"세컨드 스트라이커","simple":"fw","main":"technique","sub":"shooting","mental":"sense","team":"individual","desc":"최전방 바로 아래에서 침투와 연계를 동시에 수행하는 공격수"},
  {"id":"kp_pressing_forward","name":"프레싱 포워드","simple":"fw","main":"stamina","sub":"power","mental":"intelligence","team":"organization","desc":"전방에서 압박을 시작하고 상대 빌드업을 방해하는 공격수"},
  {"id":"kp_inside_forward_l","name":"왼쪽 인사이드 포워드","simple":"fw","main":"shooting","sub":"technique","mental":"sense","team":"individual","desc":"왼쪽에서 안쪽으로 파고들어 슈팅을 노리는 공격수"},
  {"id":"kp_inside_forward_r","name":"오른쪽 인사이드 포워드","simple":"fw","main":"shooting","sub":"technique","mental":"sense","team":"individual","desc":"오른쪽에서 중앙으로 좁혀 들어와 득점을 노리는 공격수"},
  {"id":"kp_classic_striker","name":"클래식 스트라이커","simple":"fw","main":"shooting","sub":"power","mental":"sense","team":"individual","desc":"박스 안에서 몸싸움과 마무리로 승부하는 정통 공격수"},
  {"id":"kp_regista","name":"레지스타","simple":"mf","main":"passing","sub":"technique","mental":"intelligence","team":"organization","desc":"낮은 위치에서 긴 패스와 경기 조율을 담당하는 후방 플레이메이커"},
  {"id":"kp_mezzala_l","name":"왼쪽 메짤라","simple":"mf","main":"technique","sub":"stamina","mental":"sense","team":"organization","desc":"중앙과 왼쪽 하프스페이스를 오가며 공격에 가담하는 미드필더"},
  {"id":"kp_mezzala_r","name":"오른쪽 메짤라","simple":"mf","main":"technique","sub":"stamina","mental":"sense","team":"organization","desc":"중앙과 오른쪽 하프스페이스를 오가며 공격에 가담하는 미드필더"},
  {"id":"kp_ball_winning_midfielder","name":"볼위닝 미드필더","simple":"mf","main":"defense","sub":"stamina","mental":"intelligence","team":"organization","desc":"중원에서 압박과 태클로 공을 탈취하는 미드필더"},
  {"id":"kp_carrier","name":"볼 캐리어","simple":"mf","main":"speed","sub":"technique","mental":"sense","team":"individual","desc":"공을 직접 운반하며 전진 드리블로 라인을 깨는 미드필더"},
  {"id":"kp_shadow_striker","name":"쉐도우 스트라이커","simple":"mf","main":"shooting","sub":"speed","mental":"sense","team":"individual","desc":"2선에서 늦게 침투해 득점 기회를 만드는 공격형 미드필더"},
  {"id":"kp_wide_playmaker_l","name":"왼쪽 와이드 플레이메이커","simple":"mf","main":"passing","sub":"technique","mental":"intelligence","team":"organization","desc":"왼쪽 측면에서 안쪽으로 들어와 패스와 전개를 담당"},
  {"id":"kp_wide_playmaker_r","name":"오른쪽 와이드 플레이메이커","simple":"mf","main":"passing","sub":"technique","mental":"intelligence","team":"organization","desc":"오른쪽 측면에서 안쪽으로 들어와 패스와 전개를 담당"},
  {"id":"kp_overlapping_fullback_l","name":"왼쪽 오버래핑 풀백","simple":"df","main":"stamina","sub":"speed","mental":"intelligence","team":"organization","desc":"왼쪽 측면에서 적극적으로 전진해 크로스와 지원을 담당"},
  {"id":"kp_overlapping_fullback_r","name":"오른쪽 오버래핑 풀백","simple":"df","main":"stamina","sub":"speed","mental":"intelligence","team":"organization","desc":"오른쪽 측면에서 적극적으로 전진해 크로스와 지원을 담당"},
  {"id":"kp_defensive_fullback_l","name":"왼쪽 수비형 풀백","simple":"df","main":"defense","sub":"stamina","mental":"intelligence","team":"organization","desc":"왼쪽 측면을 안정적으로 지키고 상대 윙어를 봉쇄하는 풀백"},
  {"id":"kp_defensive_fullback_r","name":"오른쪽 수비형 풀백","simple":"df","main":"defense","sub":"stamina","mental":"intelligence","team":"organization","desc":"오른쪽 측면을 안정적으로 지키고 상대 윙어를 봉쇄하는 풀백"},
  {"id":"kp_stopper_cb","name":"스토퍼 센터백","simple":"df","main":"power","sub":"defense","mental":"sense","team":"organization","desc":"강한 몸싸움과 전진 수비로 상대 공격수를 직접 제압하는 센터백"},
  {"id":"kp_libero","name":"리베로","simple":"df","main":"technique","sub":"defense","mental":"intelligence","team":"organization","desc":"수비 뒤에서 자유롭게 커버하고 공격 전개까지 돕는 수비수"},
  {"id":"kp_build_up_keeper","name":"빌드업 키퍼","simple":"gk","main":"passing","sub":"goalkeeper","mental":"intelligence","team":"organization","desc":"짧은 패스와 롱킥으로 후방 빌드업에 적극 관여하는 골키퍼"},
  {"id":"kp_line_keeper","name":"라인 키퍼","simple":"gk","main":"goalkeeper","sub":"defense","mental":"intelligence","team":"organization","desc":"골문 가까이에서 안정적인 위치 선정과 판단으로 실점을 줄이는 골키퍼"}
];
